name: Fuzz Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fuzz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install system build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev python3-setuptools python3-wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install hypothesis pandas typer ruamel.yaml jschema-to-python sarif-om

      - name: Run fuzz tests
        run: python fuzz.py
